### ISSUE TITLE
Module not found: Error: Can't resolve 'React' in '/home/capaj/git_projects/looop/project-alpha/node_modules/react-visibility-sensor/dist'

### ISSUE THREAD

**Issue by capaj** [joshwnj/react-visibility-sensor#148]
I have webpack 4 and react-visibility-sensor 5.0.2
and when I import like this:
 `import VisibilitySensor from "react-visibility-sensor"`
I get
```
ERROR in ../node_modules/react-visibility-sensor/dist/visibility-sensor.js
Module not found: Error: Can't resolve 'React' in '/home/capaj/git_projects/looop/project-alpha/node_modules/react-visibility-sensor/dist'
 @ ../node_modules/react-visibility-sensor/dist/visibility-sensor.js 4:286-324
 @ ./src/pages/student-topic-detail-page/StudentTopicDetailPage.tsx
 @ ./src/components/LooopRoutes.tsx
 @ ./src/components/App.js
 @ ./src/app/app.js
 @ ./src/index/index.js
 @ multi webpack-dev-server/client?http://localhost:4001 webpack/hot/dev-server ./src/index/index

ERROR in ../node_modules/react-visibility-sensor/dist/visibility-sensor.js
Module not found: Error: Can't resolve 'ReactDOM' in '/home/capaj/git_projects/looop/project-alpha/node_modules/react-visibility-sensor/dist'
 @ ../node_modules/react-visibility-sensor/dist/visibility-sensor.js 4:286-324
 @ ./src/pages/student-topic-detail-page/StudentTopicDetailPage.tsx
 @ ./src/components/LooopRoutes.tsx
 @ ./src/components/App.js
 @ ./src/app/app.js
 @ ./src/index/index.js
 @ multi webpack-dev-server/client?http://localhost:4001 webpack/hot/dev-server ./src/index/index
```
when I change to import the source file:
`import VisibilitySensor from 'react-visibility-sensor/visibility-sensor'`

it works great.

The webpack thingy seems to think I the app run in an UMD loader and hence it tries to load deps from globals.

**Comment by GaddMaster** [comment]
Similiar issue with react Dom not resolved ? Any activity here at all ?

**Comment by laustdeleuran** [comment]
+1, getting a similar error with `ReactDOM`:

```
ERROR in ../node_modules/react-visibility-sensor/dist/visibility-sensor.js
Module not found: Error: Can't resolve 'ReactDOM' in '/Users/USER_NAME/Sites/PROJECT_NAME/node_modules/react-visibility-sensor/dist'
resolve 'ReactDOM' in '/Users/USER_NAME/Sites/PROJECT_NAME/node_modules/react-visibility-sensor/dist'
  Parsed request is a module
  using description file: /Users/USER_NAME/Sites/PROJECT_NAME/node_modules/react-visibility-sensor/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/USER_NAME/Sites/PROJECT_NAME/node_modules/react-visibility-sensor/dist/node_modules doesn't exist or is not a directory
```

**Comment by autolistben** [comment]
I'm experiencing the same problem.  It looks like if you want webpack to transpile your node_modules then it will crash on `react-visibility-sensor`, though I am not sure exactly why.  This package is already transpiled and when webpack tries to transpile it again (which I imagine should pretty much be a no-op) it is breaking.

The suggested fix above is to import from `react-visibility-sensor/visibility-sensor` which is the un-transpiled version of the default import `react-visibility-sensor/dist/visibility-sensor` which works because that allows webpack to perform the original transpilation instead of what is provided in the package.

However, that solution did cause my jest tests to break.  I'm using `babel-jest`, which by default does not transpile node modules so now it was crashing on the un-transpiled version that I am importing.  The easiest fix appears to be to use the `transformIgnorePatters` jest config setting (https://jestjs.io/docs/en/configuration#transformignorepatterns-array-string) to transpile this package:

```
"transformIgnorePatterns": [
  "node_modules/(?!(react-native|my-project|react-native-button)/)"
]
```

But that is a lot of hacks for one package :(

**Comment by autolistben** [comment]
Actually on second thought, it is better to configure webpack to skip transpilation for `react-visibility-sensor` instead of importing was is essentially a private file.  If this package decided to change the file structure this could cause your code to crash.  So instead configure `babel-loader` as follows and leave your imports and jest config alone!

```
{
  test: /\.js?$/,
  use: {
    loader: 'babel-loader',
    options: {
      cacheDirectory: true
    },
    exclude: /node_modules\/(?!(react-visibility-sensor)\/).js$/
  }
}
```

**Comment by buz-zard** [comment]
Until this get's resolved I published https://github.com/joshwnj/react-visibility-sensor/pull/151 bundling fix 
under https://www.npmjs.com/package/@k.sh/react-visibility-sensor if anyone needs a drop-in-fix.

**Comment by afdev82** [comment]
For me it doesn't fix the problem... the first solution changing the import line nor the bundling fix

**Comment by laustdeleuran** [comment]
+1, I'm also experiencing this with `ReactDOM`. 

```
ERROR in ../node_modules/react-visibility-sensor/dist/visibility-sensor.js
Module not found: Error: Can't resolve 'ReactDOM' in '/Users/username/project_folder/node_modules/react-visibility-sensor/dist'
resolve 'ReactDOM' in '/Users/username/project_folder/node_modules/react-visibility-sensor/dist'
  Parsed request is a module
  using description file: /Users/username/project_folder/node_modules/react-visibility-sensor/package.json (relative path: ./dist)
```

I've temporarily fixed this using @autolistben's [solution](https://github.com/joshwnj/react-visibility-sensor/issues/148#issuecomment-476400979).

---

I'm importing the module using 

```
import ReactVisibilitySensor from 'react-visibility-sensor';
```

And I'm running the following versions:

*NPM*: v6.9.0
*Node*: v12.4.0
*Webpack*: v4.29.6
*babel-loader*: v8.0.5

**Comment by GaddMaster** [comment]
Pretty sure I discovered ages ago, it's because not supported yet on N browsers YET. coming soon. I used a kool repo that did job. Explain what you need and I'll share my code of it will help

**Comment by kmvan** [comment]
> Until this get's resolved I published #151 bundling fix
> under https://www.npmjs.com/package/@k.sh/react-visibility-sensor if anyone needs a drop-in-fix.

Thanks.

**Comment by pcast01** [comment]
I was able to get past this problem by referencing this stackoverflow:  [https://stackoverflow.com/questions/52013636/module-not-found-error-cant-resolve-reactdom](https://stackoverflow.com/questions/52013636/module-not-found-error-cant-resolve-reactdom) 

Creating a folder called "ReactDOM" in node_modules folder with 1 line that exports back to the real react-dom.

`export * from "react-dom";`

then in my package.json putting in a line `"ReactDOM": "ReactDom",`

I hope react-visibility-sensor is updated to use the correct react-dom also it seams it reference a bad copy of React as well.

The other issue that comes with this hack is that every time you need to do npm install then you need to delete that folder and remove the line in the package.json, update your packages then put it all back. 

Also how do I get this "drop-in-fix"? I am unable to.

> Until this get's resolved I published #151 bundling fix
> under https://www.npmjs.com/package/@k.sh/react-visibility-sensor if anyone needs a drop-in-fix.

> Thanks

**Comment by srm985** [comment]
This issue seems to stem from the webpack configuration. I'm not sure why it is written as `React` and `ReactDOM` instead of `react` and `react-dom`. This can be seen on lines [12](https://github.com/joshwnj/react-visibility-sensor/blob/master/webpack.config.js#L12) and [18](https://github.com/joshwnj/react-visibility-sensor/blob/master/webpack.config.js#L18) of `webpack.config.js`.

```js
// webpack.config.js
let externals = {
    react: {
        commonjs: "react",
        commonjs2: "react",
        amd: "React",
        root: "React"
    },
    "react-dom": {
        commonjs: "react-dom",
        commonjs2: "react-dom",
        amd: "ReactDOM",
        root: "ReactDOM"
    }
};
```

This causes a webpack output in /dist/visibility-sensor.js of:

```js
if (typeof exports === 'object' && typeof module === 'object')
    module.exports = factory(require("react"), require("react-dom"));
else if (typeof define === 'function' && define.amd)
    define(["React", "ReactDOM"], factory);  // <---------- My Problem
else if (typeof exports === 'object')
    exports["react-visibility-sensor"] = factory(require("react"), require("react-dom"));
else
    root["react-visibility-sensor"] = factory(root["React"], root["ReactDOM"]);
```

Of course these modules don't exist because they are named incorrectly. Perhaps I'm missing something, but it seems if this were changed in the webpack configuration, this would be resolved. If someone can confirm this, I'm happy to submit a PR.

Working Fix (Works for me at least...)
For me the issue only occurs when running locally with Storybook. As such, I simply modified the bundled instance. If it's breaking in production though, you need to fork and modify the webpack configuration.
For working locally only, in /dist/visibility-sensor.js, you can just modify line 5 as follows:

```
// Incorrect Syntax
define(["React", "ReactDOM"], factory);

// Correct Casing
define(["react", "react-dom"], factory);
```

**Comment by karolis-sh** [comment]
This package unmaintained and not really ready to be consumed as a es/cjs module. Ended up migrating to https://github.com/thebuilder/react-intersection-observer

**Comment by felixfbecker** [comment]
This would be fixed if the `main` field in package.json was just switched to `visibility-sensor.js` or a `module` field added pointing to it

**Comment by iamtheasad** [comment]
Import it from this directory: 

`import ReactVisibilitySensor from 'react-visibility-sensor';`
